export const themes = [
  { name: "Ambiance", code: "ambiance" },
  { name: "Chaos", code: "chaos" },
  { name: "Chrome", code: "chrome" },
  { name: "Clouds", code: "clouds" },
  { name: "Clouds Midnight", code: "clouds_midnight" },
  { name: "Crimson editor", code: "crimson_editor" },
  { name: "Dawn", code: "dawn" },
  { name: "Dracula", code: "dracula" },
  { name: "Dreamweaver", code: "dreamweaver" },
  { name: "Eclipse", code: "eclipse" },
  { name: "Github", code: "github" },
  { name: "Gob", code: "gob" },
  { name: "Gruvbox", code: "gruvbox" },
  { name: "Idle Fingers", code: "idle_fingers" },
  { name: "Iplastic", code: "iplastic" },
  { name: "Katzenmilch", code: "katzenmilch" },
  { name: "Kr Theme", code: "kr_theme" },
  { name: "Kuroir", code: "kuroir" },
  { name: "Merbivore", code: "merbivore" },
  { name: "Merbivore Soft", code: "merbivore_soft" },
  { name: "Mono Industrial", code: "mono_industrial" },
  { name: "Monokai", code: "monokai" },
  { name: "Nord Dark", code: "nord_dark" },
  { name: "One Dark", code: "one_dark" },
  { name: "Pastel On Dark", code: "pastel_on_dark" },
  { name: "solarized Dark", code: "solarized_dark" },
  { name: "solarized Light", code: "solarized_light" },
  { name: "Sqlserver", code: "sqlserver" },
  { name: "Terminal", code: "terminal" },
  { name: "Textmate", code: "textmate" },
  { name: "Tomorrow", code: "tomorrow" },
  { name: "Tomorrow Night", code: "tomorrow_night" },
  { name: "Tomorrow Night Blue", code: "tomorrow_night_blue" },
  { name: "Tomorrow Night Bright", code: "tomorrow_night_bright" },
  { name: "Tomorrow Night Eighties", code: "tomorrow_night_eighties" },
  { name: "Twilight", code: "twilight" },
  { name: "Vibrant Ink", code: "vibrant_ink" },
  { name: "Xcode", code: "xcode" },
];
